spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345678

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      format_sql: true
      show-sql: true
      ddl-auto: update
